name: design_system_sl
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0-322.0.dev <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: